version: "3.9"

services:
  # ---------- Postgres ----------
  postgres-buntodo:
    image: postgres:14
    container_name: postgres-buntodo
    environment:
      POSTGRES_USER: bunuser
      POSTGRES_PASSWORD: bunpass
      POSTGRES_DB: buntododb
    ports:
      - "5432:5432"
    volumes:
      - buntodo_pgdata:/var/lib/postgresql/data

  # ---------- Redis ----------
  redis-buntodo:
    image: redis:7
    container_name: redis-buntodo
    ports:
      - "6379:6379"
    volumes:
      - buntodo_redisdata:/data

  # ---------- Bun backend ----------
  backend-buntodo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app       # live reload
    environment:
      - DATABASE_URL=postgres://bunuser:bunpass@postgres-buntodo:5432/buntododb
      - REDIS_URL=redis://redis-buntodo:6379
      - PORT=3000
    expose:
      - "3000"         # internal container port
    deploy:
      replicas: 4      # 4 backend containers
    depends_on:
      - postgres-buntodo
      - redis-buntodo

  # ---------- Nginx ----------
  nginx-buntodo:
    image: nginx:alpine
    container_name: nginx-buntodo
    ports:
      - "8080:80"     # host port â†’ container port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-buntodo

volumes:
  buntodo_pgdata:
  buntodo_redisdata: